hydra:
  run:
    dir: outputs/${data.name}/${model.name}-${loss.name}-${optim.name}/${now:%Y%m%d-%H:%M:%S-%f}

defaults:
  - data: eyepacs
  - model: resnet50
  - loss: ce
  - optim: sgd
  - scheduler: one_cycle
  - wandb: my

  - override hydra/job_logging: custom

task: dr
device: cuda:0
seed: 1
log_period: 50
train:
  max_epoch: 100
  resume: False
  keep_checkpoint_num: 1
  keep_checkpoint_interval: 0
  mixup:
    enable: False
    alpha: 0.4
test:
  checkpoint: ""
  save_prediction: False
wandb:
  enable: True
