MODEL:
  ARCH: Unet
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  NUM_CLASSES: 6
  MODE: multilabel
  ACT_FUNC: sigmoid
DATA:
  NAME: FGADR
  DATA_ROOT: ./data/FGADR-Seg/Seg-set
  RESIZE: [896, 896]  # [896, 896]
LOSS:
  NAME: CE
SOLVER:
  OPTIMIZING_METHOD: adam
  BASE_LR: 0.0001
  MAX_EPOCH: 100
  LR_POLICY: cosine
TRAIN:
  DATA_PATH: train.txt
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  CALCULATE_METRIC: True
  # AUTO_RESUME: True
VAL:
  DATA_PATH: val.txt
  BATCH_SIZE: 8
TEST:
  DATA_PATH: test.txt
  BATCH_SIZE: 8
  CHECKPOINT_PATH: ""
WANDB:
  ENABLE: True
  PROJECT: retinal
  ENTITY: newton
OUTPUT_DIR: ./log/FGADR_baseline_bce_unet
RNG_SEED: 1
LOG_PERIOD: 30
DEVICE: cuda:0
PERFORM_TEST: True
THRES: 0.2