MODEL:
  ARCH: Unet
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  NUM_CLASSES: 8
  MODE: multilabel
  ACT_FUNC: sigmoid
DATA:
  NAME: retinal-lesions
  DATA_ROOT: ./data/retinal-lesions-v20191227
  RESIZE: [512, 512]  # [896, 896]
  LABEL_VALUES: [127, 255]
  BINARY: False
  CLASSES_PATH: ./data/retinal-lesions-v20191227/classes.txt
LOSS:
  NAME: CE
SOLVER:
  OPTIMIZING_METHOD: adam
  BASE_LR: 0.0001
  MAX_EPOCH: 100
  LR_POLICY: cosine
TRAIN:
  DATA_PATH: train.txt
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  CALCULATE_METRIC: True
VAL:
  DATA_PATH: val.txt
  BATCH_SIZE: 8
TEST:
  DATA_PATH: test.txt
  BATCH_SIZE: 8
  CHECKPOINT_PATH: ""
OUTPUT_DIR: ./log/retinal-lesions_baseline_bce
RNG_SEED: 1
LOG_PERIOD: 30
DEVICE: cuda:0
PERFORM_TEST: True