MODEL:
  ARCH: Fpn
  ENCODER: resnext101_32x8d
  ENCODER_WEIGHTS: imagenet
  NUM_CLASSES: 9
  MODE: multilabel
  ACT_FUNC: sigmoid
DATA:
  NAME: retinal-lesions
  DATA_ROOT: ./data/retinal-lesions
  RESIZE: [896, 896]
LOSS:
  NAME: CE
SOLVER:
  OPTIMIZING_METHOD: sgd 
  BASE_LR: 0.01
  MIN_LR: 1e-4
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  MAX_EPOCH: 100
  LR_POLICY: poly
TRAIN:
  DATA_PATH: train.txt
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CALCULATE_METRIC: True
VAL:
  DATA_PATH: val.txt
  BATCH_SIZE: 8
TEST:
  DATA_PATH: val.txt
  BATCH_SIZE: 8
  CHECKPOINT_PATH: ""
  BEST_CHECKPOINT: True
WANDB:
  ENABLE: False
  PROJECT: retinal
  ENTITY: newton
OUTPUT_DIR: ./log/retinal-lesions_resnext_fpn_ce
RNG_SEED: 1
LOG_PERIOD: 20
DEVICE: cuda:0
PERFORM_TEST: True
THRES: 0.2